# Generated by Django 4.1.7 on 2023-07-01 17:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("serial", "Serial")],
                        max_length=50,
                    ),
                ),
                ("rating", models.FloatField()),
                ("description", models.CharField(max_length=1200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "db_table": "movies",
            },
        ),
    ]
